version: "3.2"

services:
    blog-db:
        image: mongo
        restart: unless-stopped
#        volumes:
#            - /data/blog:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: marco
            MONGO_INITDB_ROOT_PASSWORD: icjSnpQ5Gj7VWdbuxWWkUy2qmNAuU7xC
            MONGO_INITDB_DATABASE: blog
        networks:
            - blog-net
        container_name: blog-db

    blog-api:
        image: marcojonudo/blog-api
        restart: unless-stopped
        ports:
            - 8095:8090
        environment:
            DB_USER: marco
            DB_PASS: icjSnpQ5Gj7VWdbuxWWkUy2qmNAuU7xC
            DB_IP: 217.71.207.101
            # DB_IP: blog-db
        networks:
            - blog-net
        depends_on:
            - blog-db
        container_name: blog-api

    blog:
        image: marcojonudo/blog
        restart: unless-stopped
        ports:
            - 4000:4000
#        environment:
#            DB_USER: marco
#            DB_PASS: icjSnpQ5Gj7VWdbuxWWkUy2qmNAuU7xC
#            DB_IP: blog-db
        networks:
            - blog-net
        depends_on:
            - blog-api
        container_name: blog

networks:
    blog-net:
        driver: bridge
